// Generated by genrs from file rosrust_tutorial/Hello.msg
// DO NOT EDIT!


#[allow(dead_code,non_camel_case_types,non_snake_case)]
#[derive(Clone,Debug,RustcEncodable,RustcDecodable)]
pub struct Hello {
    pub hello: ::std::string::String,
}


#[allow(dead_code,non_snake_case)]
impl Hello {
    pub fn new() -> Hello {
        Hello {
            hello: ::std::string::String::new(),
        }
    }
}


impl ::rosrust::Message for Hello {
    fn md5sum() -> ::std::string::String {
        "aa1e4c96cf56304cea7e883d117e24f3".into()
    }
    fn msg_type() -> ::std::string::String {
        "rosrust_tutorial/Hello".into()
    }
    fn msg_definition() -> ::std::string::String {
        "string hello\n\
".into()
    }

}
